#! /bin/sh

de () {
	_usage () {
		echo "Usage: devenv <cmd>"
		echo "  cmd - Bash command to sandbox."
	}

	if [ $# -eq 0 ]; then
		_usage
		return
	fi

	if [ -f 'dev.env' ]; then
		eval $(grep -v '^#' dev.env | sed 's/^/export /g')
	else
		echo "'dev.env' not found."
	fi

	if [ -f 'user.env' ]; then
		eval $(grep -v '^#' user.env | sed 's/^/export /g')
	fi

	$@
}

te () {
	_usage () {
		echo "Usage: testenv <cmd>"
		echo "  cmd - Bash command to sandbox."
	}

	if [ $# -eq 0 ]; then
		_usage
		return
	fi

	if [ -f 'dev.env' ]; then
		eval $(grep -v '^#' dev.env | sed 's/^/export /g')
	fi

	if [ -f 'test.env' ]; then
		eval $(grep -v '^#' test.env | sed 's/^/export /g')
	else
		echo "'test.env' not found."
	fi

	$@
}

xe () {
	_usage () {
		echo "Usage: xenv <env-file> <cmd>"
		echo "  env-file - Path to env file."
		echo "  cmd - Bash command to sandbox."
	}

	if [ $# -lt 2 ]; then
		_usage
		return
	fi

	if [ -f $1 ]; then
		eval $(grep -v '^#' $1 | sed 's/^/export /g')
	else
		echo "'$1' not found."
	fi

	shift

	$@
}
